# Generated by Django 4.1.2 on 2022-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='frustrations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='needs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
