# Generated by Django 4.1.2 on 2022-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0002_personamodel_frustrations_personamodel_needs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personamodel',
            name='digital_apps',
            field=models.ManyToManyField(to='personaApp.digitalapps'),
        ),
    ]
