# Generated by Django 4.1.2 on 2022-12-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0004_personality_personamodel_personality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(blank=True, max_length=25, null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personamodel',
            name='motivations',
            field=models.ManyToManyField(to='personaApp.motivation'),
        ),
    ]
