# Generated by Django 4.1.2 on 2022-12-02 04:52

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0005_motivation_personamodel_motivations'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='/pimages/images/', collection='persona_profile_images'), upload_to='entries'),
        ),
    ]
