# Generated by Django 4.1.3 on 2022-12-15 05:59

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0006_personamodel_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personamodel',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='/pimages/profileimages/', collection='persona_profile_images'), upload_to='entries'),
        ),
    ]
