# Generated by Django 4.1.2 on 2022-10-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='mobile',
            new_name='phone',
        ),
    ]
