# Generated by Django 4.1.2 on 2022-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_rename_mobile_customusers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
