# Generated by Django 4.1.2 on 2022-11-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_customusers_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsersV2',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=60, null=True, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
