# Generated by Django 4.1.2 on 2022-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_customusersv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusersv2',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusersv2',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusersv2',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
