# Generated by Django 4.1.2 on 2022-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_customusersv2_is_staff_customusersv2_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusersv2',
            name='organization',
            field=models.CharField(blank=True, default='single_user', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customusersv2',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
